### ISSUE TITLE
Error installing scikit-image

### ISSUE THREAD

**Issue by ghost** [rnnh/vaporiser#5]
thats my error while installing requirements.txt in env:

ModuleNotFoundError: No module named 'numpy'
ERROR: Could not find a version that satisfies the requirement scikit-image==0.17.2 (from versions: 0.7.2, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.9.3, 0.10.0, 0.10.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.5, 0.15.0, 0.16.2, 0.17.1, 0.17.2, 0.18.0rc0, 0.18.0rc1, 0.18.0rc2, 0.18.0, 0.18.1, 0.18.2rc1, 0.18.2rc2, 0.18.2, 0.18.3)
ERROR: No matching distribution found for scikit-image==0.17.2

And an Error while running:
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\VAPORISER\vaporiser.py", line 4, in <module>
    from pysndfx import AudioEffectsChain
ModuleNotFoundError: No module named 'pysndfx'

after installing pysndfx this Error appears:
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\VAPORISER\vaporiser.py", line 5, in <module>
    from skimage.filters import sobel
ModuleNotFoundError: No module named 'skimage'

and skimage / scikit-image can't be installed because of the first error

Any Help is fine!
Thanks

**Comment by rnnh** [comment]
Thanks very much for bringing this to my attention, I am glad that someone is interested in using this script! I have only tested this script on Linux until now, but I will let you know when I have it working on Windows. The following checklist is for my own reference, I will mark off the tasks as I complete them.

# Vaporiser for Windows

- [x] Run `vaporiser.py` on Windows

- [x] Ensure virtual environment for `vaporiser.py` on Windows can be replicated

- [x] Update `README.md` with instructions for using `vaporiser.py` on Windows

**Comment by rnnh** [comment]
Dear @Waterfisch,

I hope you are well! I have added instructions for [using vaporiser on Windows](https://github.com/rnnh/vaporiser#using-vaporiser-on-windows). In short, `vaporiser.py` cannot be used on Windows alone, but it can be used through [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/about) or a [Linux virtual machine.](https://ubuntu.com/tutorials/how-to-run-ubuntu-desktop-on-a-virtual-machine-using-virtualbox) While I was able to create a Python virtual environment for this script and run it on Windows, it did not perform as intended. This is because [MP3 support for Sound eXchange (SoX)](https://pkgs.org/download/libsox-fmt-mp3)- one of the system requirements for this script- is not available for Windows: without SoX MP3 support, the audio effects cannot be applied to MP3 files.

Thanks again for bringing this to my attention. As I said, I had not considered Windows users when I initially wrote this script; hopefully more people will be able to use it now. If you encounter any other errors while using this project, or have any questions, please feel free to let me know.

Kind regards,
Ronan
